### ISSUE TITLE
tracking things needed for pub

### ISSUE THREAD

**Issue by ppxasjsm** [Edinburgh-Chemistry-Teaching/Data-driven-chemistry#40]
- [x] some blurb for instructors on how to use the material (maybe as a readme?)
- [x] Add citation for carpentries resource
- [x] Maybe improve contribution guidelines further
- [x] Make sure colab works for all notebooks
    - [x] Unit_01
     - [x] Unit_02
     - [x] Unit_03
     - [x] Unit_04
     - [x] Unit_05
     - [x] Unit_06
     - [x] Unit_07
     - [x] Unit_08
     - [x] Unit_09
     - [x] Unit_10
- [x] make sure using the environment mention in install section works for all notebooks:
     - [x] Unit_01
     - [x] Unit_02
     - [x] Unit_03
     - [x] Unit_04
     - [x] Unit_05
     - [x] Unit_06
     - [x] Unit_07
     - [x] Unit_08
     - [x] Unit_09
     - [x] Unit_10
 - [x] Wait for thoughts on FIXME
